### ISSUE TITLE
Helpdesk cronjob no longer fetches emails

### ISSUE THREAD

**Issue by malemburg** [EuroPython/ep-helpdesk#5]
The helpdesk no longer polls emails from the POP email accounts.

Running the fetch script manually reveals the problem:

```
Traceback (most recent call last):
  File "/usr/src/helpdesk/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 58, in handle
    process_email(quiet=quiet)
  File "/usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 78, in process_email
    process_queue(q, quiet=quiet)
  File "/usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 127, in process_queue
    ticket = ticket_from_message(message=full_message, queue=q, quiet=quiet)
  File "/usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 176, in ticket_from_message
    subject = decode_mail_headers(decodeUnknown(message.get_charset(), subject))
  File "/usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 169, in decode_mail_headers
    return u' '.join([unicode(msg, charset or 'utf-8') for msg, charset in decoded])
UnicodeDecodeError: 'gb2312' codec can't decode bytes in position 0-1: illegal multibyte sequence
```

So apparently, the get_email.py script is not flexible enough to work with malformed emails.

**Comment by malemburg** [comment]
As quick fix, I edited /usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py to make it more robust, but this change will be overwritten next time the container is recreated:

```
def decodeUnknown(charset, string):
    if not charset:
        try:
            return string.decode('utf-8','ignore')
        except:
            return string.decode('iso8859-1','ignore')
    try:
        return unicode(string, charset)
    except (LookupError, UnicodeDecodeError):
        return unicode(string, 'utf-8', 'replace')

def decode_mail_headers(string):
    decoded = decode_header(string)
    return u' '.join([unicode(msg, charset or 'utf-8', 'replace') for msg, charset in decoded])
```

**Comment by malemburg** [comment]
It's still working, but only a question of time until it will start failing again.

**Comment by malemburg** [comment]
Failed again today, since the containers were rebuilt:

```
Processing: EuroPython 2016 Helpdesk
Traceback (most recent call last):
  File "/usr/src/helpdesk/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 58, in handle
    process_email(quiet=quiet)
  File "/usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 78, in process_email
    process_queue(q, quiet=quiet)
  File "/usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 127, in process_queue
    ticket = ticket_from_message(message=full_message, queue=q, quiet=quiet)
  File "/usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 214, in ticket_from_message
    body_plain = EmailReplyParser.parse_reply(decodeUnknown(part.get_content_charset(), part.get_payload(decode=True)))
  File "/usr/local/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 165, in decodeUnknown
    return unicode(string, charset)
UnicodeDecodeError: 'gb2312' codec can't decode bytes in position 2020-2021: illegal multibyte sequence
```

**Comment by malemburg** [comment]
Reapplied above hotfix.

**Comment by malemburg** [comment]
This was fixed in the latest version of the helpdesk app, but in a slightly different way:

```
            try:
                return string.decode('utf-8', 'ignore')
            except:
                return string.decode('iso8859-1', 'ignore')
``` 

Oh, well.
